// Shared game state enum — separate file to avoid circular imports
export const GameState = {
  TITLE: 'TITLE',
  RUNNING: 'RUNNING',
  GATEKEEPER_CHALLENGE: 'GATEKEEPER_CHALLENGE',
  BRIDGE_BUILDING: 'BRIDGE_BUILDING',
  BRIDGE_COLLAPSE: 'BRIDGE_COLLAPSE',
  BRIDGE_CROSSING: 'BRIDGE_CROSSING',
  LEVEL_COMPLETE: 'LEVEL_COMPLETE',
  GAME_OVER: 'GAME_OVER',
  VICTORY: 'VICTORY',
  DICTIONARY_MODE: 'DICTIONARY_MODE',
  SANDBOX: 'SANDBOX',
};
